# NOTE: This docker-compose.yml is meant to be just an example of how
# you could accomplish this on your own. It is not intended to work in
# all use-cases and must be adapted to fit your needs. This is merely
# a guideline.

# See docs.getsentry.com/on-premise/server/ for full
# instructions

version: "3"

services:
  smtp:
    restart: always
    image: tianon/exim4

  memcached:
    restart: always
    image: memcached:1.4

  redis:
    restart: always
    image: redis:3.2-alpine

  postgres:
    restart: always
    image: postgres:9.5
    volumes:
      - sentry-postgres:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/db-files

  upgrade:
    restart: always
    image: <YOUR_IMAGE_LINK>
    depends_on:
      - redis
      - postgres
      - memcached
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      SENTRY_SECRET_KEY: <YOUR_SECRET_KEY>
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - sentry-data:/var/lib/sentry/files
    command: upgrade

  web:
    restart: always
    image: <YOUR_IMAGE_LINK>
    depends_on:
      - upgrade

    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      SENTRY_SECRET_KEY: <YOUR_SECRET_KEY>
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - sentry-data:/var/lib/sentry/files
    ports:
      - '9000:9000'

  cron:
    restart: always
    image: <YOUR_IMAGE_LINK>
    depends_on:
      - upgrade

    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      SENTRY_SECRET_KEY: <YOUR_SECRET_KEY>
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - sentry-data:/var/lib/sentry/files
    command: run cron

  worker:
    restart: always
    image: <YOUR_IMAGE_LINK>
    depends_on:
      - upgrade

    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      SENTRY_SECRET_KEY: <YOUR_SECRET_KEY>
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - sentry-data:/var/lib/sentry/files
    command: run worker

volumes:
  sentry-data:
  sentry-postgres:
